
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-08-31T13:47:10+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "b47b593c8b17ee0bd972050804ff417ff8633396",
 "version": "0.4.5"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
