# Generated by Django 4.0.5 on 2022-08-14 20:10

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0005_alter_figure_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='dashboard',
            name='backgroundColor',
            field=colorfield.fields.ColorField(default='#FF0000', image_field=None, max_length=18, samples=None),
        ),
    ]
