
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-08-30T11:49:58+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "dfdf170f9af9234eff3a50a2ea00f51f4b34df78",
 "version": "0.7.1.post.dev746"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
