# coding: utf-8

"""
    vsc

    Provides VSC APIs  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import vsc
from vsc.models.new_volume_request import NewVolumeRequest  # noqa: E501
from vsc.rest import ApiException


class TestNewVolumeRequest(unittest.TestCase):
    """NewVolumeRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testNewVolumeRequest(self):
        """Test NewVolumeRequest"""
        # FIXME: construct object with mandatory attributes with example values
        # model = vsc.models.new_volume_request.NewVolumeRequest()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
