class Defines:
    KILOBYTE_GIGABYTE_CONVERSION = 1048576
    SECOND_DAY_CONVERSION = 86400
    SECOND_HOUR_CONVERSION = 3600
    SECOND_MINUTE_CONVERSION = 60
    HOUR_DAY_CONVERSION = 24   
    MINUTE_HOUR_CONVERSION = 60