
# This file was generated by 'versioneer.py' (0.23.dev0) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-08-28T13:19:09-0500",
 "dirty": false,
 "error": null,
 "full-revisionid": "d7fb940264a392857781b075e1b8178c603001a2",
 "version": "2.8.2.dev20220829"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
