# coding: utf-8

"""
    PP api

    PP operations  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import pp
from pp.models.body9 import Body9  # noqa: E501
from pp.rest import ApiException


class TestBody9(unittest.TestCase):
    """Body9 unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testBody9(self):
        """Test Body9"""
        # FIXME: construct object with mandatory attributes with example values
        # model = pp.models.body9.Body9()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
