# coding: utf-8

"""
    PP api

    PP operations  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import pp
from pp.models.body24 import Body24  # noqa: E501
from pp.rest import ApiException


class TestBody24(unittest.TestCase):
    """Body24 unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testBody24(self):
        """Test Body24"""
        # FIXME: construct object with mandatory attributes with example values
        # model = pp.models.body24.Body24()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
