
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-09-02T08:50:21-0700",
 "dirty": false,
 "error": null,
 "full-revisionid": "993e389636f975c4a6178e91c149c95e97b868d0",
 "version": "4.1.26"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
