# Generated by Django 4.1 on 2022-08-30 15:53

from django.db import migrations, models
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('task_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('name', models.TextField()),
                ('args', models.TextField()),
                ('payload', models.BinaryField()),
                ('tries', models.IntegerField(default=0)),
                ('next_try', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_error', models.TextField(blank=True, null=True)),
                ('queue', models.TextField(default='default')),
                ('priority', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='TaskResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('name', models.TextField()),
                ('args', models.TextField()),
                ('payload', models.BinaryField()),
                ('queue', models.TextField()),
                ('result', models.BinaryField(blank=True, null=True)),
                ('error', models.TextField(blank=True, null=True)),
                ('started', models.DateTimeField()),
                ('finished', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
