# coding: utf-8

"""
    ZIOS api

    ZIOS operations  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import zios
from zios.api.load_balancer_api import LoadBalancerApi  # noqa: E501
from zios.rest import ApiException


class TestLoadBalancerApi(unittest.TestCase):
    """LoadBalancerApi unit test stubs"""

    def setUp(self):
        self.api = zios.api.load_balancer_api.LoadBalancerApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_get_iop_metering_load_balancer_group(self):
        """Test case for get_iop_metering_load_balancer_group

        """
        pass

    def test_get_latency_metering_load_balancer_group(self):
        """Test case for get_latency_metering_load_balancer_group

        """
        pass

    def test_get_load_balancer_group(self):
        """Test case for get_load_balancer_group

        """
        pass

    def test_get_load_balancer_groups(self):
        """Test case for get_load_balancer_groups

        """
        pass

    def test_get_throughput_metering_load_balancer_group(self):
        """Test case for get_throughput_metering_load_balancer_group

        """
        pass


if __name__ == '__main__':
    unittest.main()
