# coding: utf-8

"""
    ZIOS api

    ZIOS operations  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import zios
from zios.models.inline_response20037_response_user_zios_data import InlineResponse20037ResponseUserZiosData  # noqa: E501
from zios.rest import ApiException


class TestInlineResponse20037ResponseUserZiosData(unittest.TestCase):
    """InlineResponse20037ResponseUserZiosData unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testInlineResponse20037ResponseUserZiosData(self):
        """Test InlineResponse20037ResponseUserZiosData"""
        # FIXME: construct object with mandatory attributes with example values
        # model = zios.models.inline_response20037_response_user_zios_data.InlineResponse20037ResponseUserZiosData()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
