# coding: utf-8

"""
    ZIOS api

    ZIOS operations  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import zios
from zios.models.inline_response20047_response import InlineResponse20047Response  # noqa: E501
from zios.rest import ApiException


class TestInlineResponse20047Response(unittest.TestCase):
    """InlineResponse20047Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testInlineResponse20047Response(self):
        """Test InlineResponse20047Response"""
        # FIXME: construct object with mandatory attributes with example values
        # model = zios.models.inline_response20047_response.InlineResponse20047Response()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
