# coding: utf-8

"""
    ZIOS api

    ZIOS operations  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import zios
from zios.models.body23 import Body23  # noqa: E501
from zios.rest import ApiException


class TestBody23(unittest.TestCase):
    """Body23 unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testBody23(self):
        """Test Body23"""
        # FIXME: construct object with mandatory attributes with example values
        # model = zios.models.body23.Body23()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
