# coding: utf-8

"""
    ZIOS api

    ZIOS operations  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import zios
from zios.models.inline_response2001_response import InlineResponse2001Response  # noqa: E501
from zios.rest import ApiException


class TestInlineResponse2001Response(unittest.TestCase):
    """InlineResponse2001Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testInlineResponse2001Response(self):
        """Test InlineResponse2001Response"""
        # FIXME: construct object with mandatory attributes with example values
        # model = zios.models.inline_response2001_response.InlineResponse2001Response()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
