# coding: utf-8

"""
    ZIOS api

    ZIOS operations  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import zios
from zios.models.body41 import Body41  # noqa: E501
from zios.rest import ApiException


class TestBody41(unittest.TestCase):
    """Body41 unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testBody41(self):
        """Test Body41"""
        # FIXME: construct object with mandatory attributes with example values
        # model = zios.models.body41.Body41()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
