# coding: utf-8

"""
    ZIOS api

    ZIOS operations  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import zios
from zios.api.logs_api import LogsApi  # noqa: E501
from zios.rest import ApiException


class TestLogsApi(unittest.TestCase):
    """LogsApi unit test stubs"""

    def setUp(self):
        self.api = zios.api.logs_api.LogsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_get_access_logs(self):
        """Test case for get_access_logs

        """
        pass

    def test_get_log(self):
        """Test case for get_log

        """
        pass


if __name__ == '__main__':
    unittest.main()
