
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-08-26T15:52:38+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "aaa2af293523647cb435a9e14921acfc35eaa789",
 "version": "2022.1.1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
