# coding: utf-8

"""
    ZIOS api

    ZIOS operations  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six

from zios.configuration import Configuration


class Body36(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'upload_rate_per_gb': 'str',
        'download_rate_per_gb': 'str'
    }

    attribute_map = {
        'upload_rate_per_gb': 'upload_rate_per_gb',
        'download_rate_per_gb': 'download_rate_per_gb'
    }

    def __init__(self, upload_rate_per_gb=None, download_rate_per_gb=None, _configuration=None):  # noqa: E501
        """Body36 - a model defined in Swagger"""  # noqa: E501
        if _configuration is None:
            _configuration = Configuration()
        self._configuration = _configuration

        self._upload_rate_per_gb = None
        self._download_rate_per_gb = None
        self.discriminator = None

        if upload_rate_per_gb is not None:
            self.upload_rate_per_gb = upload_rate_per_gb
        if download_rate_per_gb is not None:
            self.download_rate_per_gb = download_rate_per_gb

    @property
    def upload_rate_per_gb(self):
        """Gets the upload_rate_per_gb of this Body36.  # noqa: E501


        :return: The upload_rate_per_gb of this Body36.  # noqa: E501
        :rtype: str
        """
        return self._upload_rate_per_gb

    @upload_rate_per_gb.setter
    def upload_rate_per_gb(self, upload_rate_per_gb):
        """Sets the upload_rate_per_gb of this Body36.


        :param upload_rate_per_gb: The upload_rate_per_gb of this Body36.  # noqa: E501
        :type: str
        """

        self._upload_rate_per_gb = upload_rate_per_gb

    @property
    def download_rate_per_gb(self):
        """Gets the download_rate_per_gb of this Body36.  # noqa: E501


        :return: The download_rate_per_gb of this Body36.  # noqa: E501
        :rtype: str
        """
        return self._download_rate_per_gb

    @download_rate_per_gb.setter
    def download_rate_per_gb(self, download_rate_per_gb):
        """Sets the download_rate_per_gb of this Body36.


        :param download_rate_per_gb: The download_rate_per_gb of this Body36.  # noqa: E501
        :type: str
        """

        self._download_rate_per_gb = download_rate_per_gb

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(Body36, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, Body36):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, Body36):
            return True

        return self.to_dict() != other.to_dict()
