# coding: utf-8

"""
    PP api

    PP operations  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import pp
from pp.models.inline_response20018_engine import InlineResponse20018Engine  # noqa: E501
from pp.rest import ApiException


class TestInlineResponse20018Engine(unittest.TestCase):
    """InlineResponse20018Engine unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testInlineResponse20018Engine(self):
        """Test InlineResponse20018Engine"""
        # FIXME: construct object with mandatory attributes with example values
        # model = pp.models.inline_response20018_engine.InlineResponse20018Engine()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
