# coding: utf-8

"""
    PP api

    PP operations  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import pp
from pp.models.body15 import Body15  # noqa: E501
from pp.rest import ApiException


class TestBody15(unittest.TestCase):
    """Body15 unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testBody15(self):
        """Test Body15"""
        # FIXME: construct object with mandatory attributes with example values
        # model = pp.models.body15.Body15()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
