# coding: utf-8

"""
    PP api

    PP operations  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import pp
from pp.models.body13 import Body13  # noqa: E501
from pp.rest import ApiException


class TestBody13(unittest.TestCase):
    """Body13 unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testBody13(self):
        """Test Body13"""
        # FIXME: construct object with mandatory attributes with example values
        # model = pp.models.body13.Body13()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
