# Generated by Django 4.0.5 on 2022-06-30 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PortForward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default='[new]', max_length=64, null=True, verbose_name='备注')),
                ('lhost', models.CharField(default='0.0.0.0', max_length=64, verbose_name='本机IP')),
                ('lport', models.IntegerField(verbose_name='本机端口')),
                ('rhost', models.CharField(max_length=32, verbose_name='远程IP')),
                ('rport', models.IntegerField(verbose_name='远程端口')),
                ('proto', models.CharField(blank=True, choices=[('tcp', 'tcp'), ('udp', 'udp')], default='tcp', max_length=32, null=True, verbose_name='网络协议类型')),
                ('enabled', models.BooleanField(default=True, verbose_name='启用')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '端口转发',
                'verbose_name_plural': '端口转发',
            },
        ),
        migrations.CreateModel(
            name='SshHost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default=None, max_length=64, null=True, verbose_name='备注')),
                ('host', models.CharField(max_length=64, verbose_name='主机名')),
                ('port', models.IntegerField(default=22, verbose_name='端口')),
                ('user', models.CharField(max_length=32, verbose_name='用户名')),
                ('password', models.CharField(max_length=32, verbose_name='密码')),
                ('private_key', models.TextField(blank=True, default=None, null=True, verbose_name='私钥')),
                ('tag', models.CharField(blank=True, default=None, max_length=16, null=True, verbose_name='标签分类')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'SSH主机',
                'verbose_name_plural': 'SSH主机',
            },
        ),
    ]
