# coding: utf-8

"""
    CC api

    Command Center operations  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import cc
from cc.models.inline_response20039_drives_drive import InlineResponse20039DrivesDrive  # noqa: E501
from cc.rest import ApiException


class TestInlineResponse20039DrivesDrive(unittest.TestCase):
    """InlineResponse20039DrivesDrive unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testInlineResponse20039DrivesDrive(self):
        """Test InlineResponse20039DrivesDrive"""
        # FIXME: construct object with mandatory attributes with example values
        # model = cc.models.inline_response20039_drives_drive.InlineResponse20039DrivesDrive()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
