# coding: utf-8

"""
    CC api

    Command Center operations  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import cc
from cc.models.inline_response20010_comments import InlineResponse20010Comments  # noqa: E501
from cc.rest import ApiException


class TestInlineResponse20010Comments(unittest.TestCase):
    """InlineResponse20010Comments unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testInlineResponse20010Comments(self):
        """Test InlineResponse20010Comments"""
        # FIXME: construct object with mandatory attributes with example values
        # model = cc.models.inline_response20010_comments.InlineResponse20010Comments()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
