# coding: utf-8

"""
    CC api

    Command Center operations  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import cc
from cc.models.inline_response20022_performances import InlineResponse20022Performances  # noqa: E501
from cc.rest import ApiException


class TestInlineResponse20022Performances(unittest.TestCase):
    """InlineResponse20022Performances unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testInlineResponse20022Performances(self):
        """Test InlineResponse20022Performances"""
        # FIXME: construct object with mandatory attributes with example values
        # model = cc.models.inline_response20022_performances.InlineResponse20022Performances()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
