# coding: utf-8

"""
    CC api

    Command Center operations  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import cc
from cc.models.body5 import Body5  # noqa: E501
from cc.rest import ApiException


class TestBody5(unittest.TestCase):
    """Body5 unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testBody5(self):
        """Test Body5"""
        # FIXME: construct object with mandatory attributes with example values
        # model = cc.models.body5.Body5()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
