# coding: utf-8

"""
    CC api

    Command Center operations  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import cc
from cc.models.inline_response20025 import InlineResponse20025  # noqa: E501
from cc.rest import ApiException


class TestInlineResponse20025(unittest.TestCase):
    """InlineResponse20025 unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testInlineResponse20025(self):
        """Test InlineResponse20025"""
        # FIXME: construct object with mandatory attributes with example values
        # model = cc.models.inline_response20025.InlineResponse20025()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
