# coding: utf-8

"""
    VPSA api

    VPSA operations  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import vpsa
from vpsa.models.inline_response20087_response import InlineResponse20087Response  # noqa: E501
from vpsa.rest import ApiException


class TestInlineResponse20087Response(unittest.TestCase):
    """InlineResponse20087Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testInlineResponse20087Response(self):
        """Test InlineResponse20087Response"""
        # FIXME: construct object with mandatory attributes with example values
        # model = vpsa.models.inline_response20087_response.InlineResponse20087Response()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
