# coding: utf-8

"""
    VPSA api

    VPSA operations  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import vpsa
from vpsa.models.inline_response200151 import InlineResponse200151  # noqa: E501
from vpsa.rest import ApiException


class TestInlineResponse200151(unittest.TestCase):
    """InlineResponse200151 unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testInlineResponse200151(self):
        """Test InlineResponse200151"""
        # FIXME: construct object with mandatory attributes with example values
        # model = vpsa.models.inline_response200151.InlineResponse200151()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
