# coding: utf-8

"""
    VPSA api

    VPSA operations  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import vpsa
from vpsa.api.remote_object_storage_api import RemoteObjectStorageApi  # noqa: E501
from vpsa.rest import ApiException


class TestRemoteObjectStorageApi(unittest.TestCase):
    """RemoteObjectStorageApi unit test stubs"""

    def setUp(self):
        self.api = vpsa.api.remote_object_storage_api.RemoteObjectStorageApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_backup_jobs_rate_limit(self):
        """Test case for backup_jobs_rate_limit

        """
        pass

    def test_backup_jobs_update_compression(self):
        """Test case for backup_jobs_update_compression

        """
        pass

    def test_break_ros_backup_job(self):
        """Test case for break_ros_backup_job

        """
        pass

    def test_break_ros_restore_job(self):
        """Test case for break_ros_restore_job

        """
        pass

    def test_change_ros_restore_job_mode(self):
        """Test case for change_ros_restore_job_mode

        """
        pass

    def test_create_ros_backup_job(self):
        """Test case for create_ros_backup_job

        """
        pass

    def test_create_ros_destination(self):
        """Test case for create_ros_destination

        """
        pass

    def test_create_ros_restore_job(self):
        """Test case for create_ros_restore_job

        """
        pass

    def test_get_all_ros_backup_jobs(self):
        """Test case for get_all_ros_backup_jobs

        """
        pass

    def test_get_all_ros_destination_backup_jobs(self):
        """Test case for get_all_ros_destination_backup_jobs

        """
        pass

    def test_get_all_ros_destination_restore_jobs(self):
        """Test case for get_all_ros_destination_restore_jobs

        """
        pass

    def test_get_all_ros_destinations(self):
        """Test case for get_all_ros_destinations

        """
        pass

    def test_get_all_ros_restore_jobs(self):
        """Test case for get_all_ros_restore_jobs

        """
        pass

    def test_get_ros_backup_job(self):
        """Test case for get_ros_backup_job

        """
        pass

    def test_get_ros_backup_job_performance(self):
        """Test case for get_ros_backup_job_performance

        """
        pass

    def test_get_ros_destination(self):
        """Test case for get_ros_destination

        """
        pass

    def test_get_ros_restore_job(self):
        """Test case for get_ros_restore_job

        """
        pass

    def test_get_ros_restore_job_performance(self):
        """Test case for get_ros_restore_job_performance

        """
        pass

    def test_pause_ros_backup_job(self):
        """Test case for pause_ros_backup_job

        """
        pass

    def test_pause_ros_restore_job(self):
        """Test case for pause_ros_restore_job

        """
        pass

    def test_remove_ros_destination(self):
        """Test case for remove_ros_destination

        """
        pass

    def test_replace_ros_backup_job_snapshot_policy(self):
        """Test case for replace_ros_backup_job_snapshot_policy

        """
        pass

    def test_resume_ros_backup_job(self):
        """Test case for resume_ros_backup_job

        """
        pass

    def test_resume_ros_restore_job(self):
        """Test case for resume_ros_restore_job

        """
        pass

    def test_set_obs_backup_job_class(self):
        """Test case for set_obs_backup_job_class

        """
        pass

    def test_update_ros_destination(self):
        """Test case for update_ros_destination

        """
        pass


if __name__ == '__main__':
    unittest.main()
