# coding: utf-8

"""
    VPSA api

    VPSA operations  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import vpsa
from vpsa.models.inline_response20028_response import InlineResponse20028Response  # noqa: E501
from vpsa.rest import ApiException


class TestInlineResponse20028Response(unittest.TestCase):
    """InlineResponse20028Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testInlineResponse20028Response(self):
        """Test InlineResponse20028Response"""
        # FIXME: construct object with mandatory attributes with example values
        # model = vpsa.models.inline_response20028_response.InlineResponse20028Response()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
