# coding: utf-8

"""
    VPSA api

    VPSA operations  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import vpsa
from vpsa.models.inline_response2003_response_policy_oas import InlineResponse2003ResponsePolicyOas  # noqa: E501
from vpsa.rest import ApiException


class TestInlineResponse2003ResponsePolicyOas(unittest.TestCase):
    """InlineResponse2003ResponsePolicyOas unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testInlineResponse2003ResponsePolicyOas(self):
        """Test InlineResponse2003ResponsePolicyOas"""
        # FIXME: construct object with mandatory attributes with example values
        # model = vpsa.models.inline_response2003_response_policy_oas.InlineResponse2003ResponsePolicyOas()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
