# coding: utf-8

"""
    VPSA api

    VPSA operations  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import vpsa
from vpsa.models.inline_response200146_response_volumes import InlineResponse200146ResponseVolumes  # noqa: E501
from vpsa.rest import ApiException


class TestInlineResponse200146ResponseVolumes(unittest.TestCase):
    """InlineResponse200146ResponseVolumes unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testInlineResponse200146ResponseVolumes(self):
        """Test InlineResponse200146ResponseVolumes"""
        # FIXME: construct object with mandatory attributes with example values
        # model = vpsa.models.inline_response200146_response_volumes.InlineResponse200146ResponseVolumes()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
