# coding: utf-8

"""
    VPSA api

    VPSA operations  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import vpsa
from vpsa.models.inline_response200128 import InlineResponse200128  # noqa: E501
from vpsa.rest import ApiException


class TestInlineResponse200128(unittest.TestCase):
    """InlineResponse200128 unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testInlineResponse200128(self):
        """Test InlineResponse200128"""
        # FIXME: construct object with mandatory attributes with example values
        # model = vpsa.models.inline_response200128.InlineResponse200128()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
