# coding: utf-8

"""
    VPSA api

    VPSA operations  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import vpsa
from vpsa.models.inline_response20087_response_src import InlineResponse20087ResponseSrc  # noqa: E501
from vpsa.rest import ApiException


class TestInlineResponse20087ResponseSrc(unittest.TestCase):
    """InlineResponse20087ResponseSrc unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testInlineResponse20087ResponseSrc(self):
        """Test InlineResponse20087ResponseSrc"""
        # FIXME: construct object with mandatory attributes with example values
        # model = vpsa.models.inline_response20087_response_src.InlineResponse20087ResponseSrc()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
