# coding: utf-8

"""
    VPSA api

    VPSA operations  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import vpsa
from vpsa.models.inline_response20022_response import InlineResponse20022Response  # noqa: E501
from vpsa.rest import ApiException


class TestInlineResponse20022Response(unittest.TestCase):
    """InlineResponse20022Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testInlineResponse20022Response(self):
        """Test InlineResponse20022Response"""
        # FIXME: construct object with mandatory attributes with example values
        # model = vpsa.models.inline_response20022_response.InlineResponse20022Response()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
