# coding: utf-8

"""
    VPSA api

    VPSA operations  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import vpsa
from vpsa.models.inline_response20050_response import InlineResponse20050Response  # noqa: E501
from vpsa.rest import ApiException


class TestInlineResponse20050Response(unittest.TestCase):
    """InlineResponse20050Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testInlineResponse20050Response(self):
        """Test InlineResponse20050Response"""
        # FIXME: construct object with mandatory attributes with example values
        # model = vpsa.models.inline_response20050_response.InlineResponse20050Response()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
