# coding: utf-8

"""
    VPSA api

    VPSA operations  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import vpsa
from vpsa.models.inline_response20063_response_vpsa_mirror_jobs import InlineResponse20063ResponseVpsaMirrorJobs  # noqa: E501
from vpsa.rest import ApiException


class TestInlineResponse20063ResponseVpsaMirrorJobs(unittest.TestCase):
    """InlineResponse20063ResponseVpsaMirrorJobs unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testInlineResponse20063ResponseVpsaMirrorJobs(self):
        """Test InlineResponse20063ResponseVpsaMirrorJobs"""
        # FIXME: construct object with mandatory attributes with example values
        # model = vpsa.models.inline_response20063_response_vpsa_mirror_jobs.InlineResponse20063ResponseVpsaMirrorJobs()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
