
# This file was generated by 'versioneer.py' (0.17) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-08-30T07:32:23+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "50a364bd884cf608d6809b9ad4f4c93b9261dbfd",
 "version": "v0.18a6"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
