VERSION_YEAR = 2022
VERSION_MONTH = int('08')
VERSION_DAY = int('30')
VERSION_HOUR = int('06')
VERSION_MINUTE = int('32')
MAJOR_VERSION = 0
MINOR_VERSION = 8
PATCH_VERSION = 202208300632
version_date = '2022/08/30 06:32'
version = '{}.{}.{}'.format(MAJOR_VERSION, MINOR_VERSION, PATCH_VERSION)
__all__  = ['MAJOR_VERSION', 'MINOR_VERSION', 'PATCH_VERSION', 'version_date', 'version']
