VERSION_YEAR = 2022
VERSION_MONTH = int('08')
VERSION_DAY = int('30')
VERSION_HOUR = int('03')
VERSION_MINUTE = int('16')
MAJOR_VERSION = 0
MINOR_VERSION = 8
PATCH_VERSION = 202208300316
version_date = '2022/08/30 03:16'
version = '{}.{}.{}'.format(MAJOR_VERSION, MINOR_VERSION, PATCH_VERSION)
__all__  = ['MAJOR_VERSION', 'MINOR_VERSION', 'PATCH_VERSION', 'version_date', 'version']
