
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-09-01T15:51:04-0400",
 "dirty": false,
 "error": null,
 "full-revisionid": "3291f90c56180ee6b40ed5bf8dd432c144ed5437",
 "version": "4.7.29"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
