# autogenerated
# mypy: ignore-errors
# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: protos/rime_configs/rime_configs.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n&protos/rime_configs/rime_configs.proto\x12\x04rime\"\x8f\x01\n\x1cPathTabularIncrementalConfig\x12\x11\n\teval_path\x18\x01 \x01(\t\x12\x15\n\rtimestamp_col\x18\x02 \x01(\t\x12\x1b\n\x0e\x65val_pred_path\x18\x03 \x01(\tH\x00\x88\x01\x01\x12\x15\n\rinclude_model\x18\x04 \x01(\x08\x42\x11\n\x0f_eval_pred_path\"t\n\x18PathNLPIncrementalConfig\x12\x11\n\teval_path\x18\x01 \x01(\t\x12\x1b\n\x0e\x65val_pred_path\x18\x02 \x01(\tH\x00\x88\x01\x01\x12\x15\n\rinclude_model\x18\x03 \x01(\x08\x42\x11\n\x0f_eval_pred_path\"w\n\x1bPathImagesIncrementalConfig\x12\x11\n\teval_path\x18\x01 \x01(\t\x12\x1b\n\x0e\x65val_pred_path\x18\x02 \x01(\tH\x00\x88\x01\x01\x12\x15\n\rinclude_model\x18\x03 \x01(\x08\x42\x11\n\x0f_eval_pred_path\"\xd6\x01\n\x1e\x44\x61taCollectorIncrementalConfig\x12V\n\x0e\x65val_data_info\x18\x01 \x01(\x0b\x32>.rime.DataCollectorIncrementalConfig.DataCollectorEvalDataInfo\x12\x15\n\rinclude_model\x18\x02 \x01(\x08\x1a\x41\n\x19\x44\x61taCollectorEvalDataInfo\x12\x12\n\nstart_time\x18\x01 \x01(\x03\x12\x10\n\x08\x65nd_time\x18\x02 \x01(\x03:\x02\x18\x01\"\x83\x02\n\x1a\x44\x65ltaLakeIncrementalConfig\x12\x45\n\x0e\x65val_data_info\x18\x01 \x01(\x0b\x32-.rime.DeltaLakeIncrementalConfig.EvalDataInfo\x12\x15\n\rinclude_model\x18\x02 \x01(\x08\x1a\x86\x01\n\x0c\x45valDataInfo\x12\x17\n\x0fserver_hostname\x18\x01 \x01(\t\x12\x11\n\thttp_path\x18\x02 \x01(\t\x12\x12\n\ntable_name\x18\x03 \x01(\t\x12\x12\n\nstart_time\x18\x04 \x01(\x03\x12\x10\n\x08\x65nd_time\x18\x05 \x01(\x03\x12\x10\n\x08time_col\x18\x06 \x01(\t\"\xd7\x01\n\x1d\x43ustomLoaderIncrementalConfig\x12H\n\x0e\x65val_data_info\x18\x01 \x01(\x0b\x32\x30.rime.CustomLoaderIncrementalConfig.EvalDataInfo\x12\x15\n\rinclude_model\x18\x02 \x01(\x08\x1aU\n\x0c\x45valDataInfo\x12\x11\n\tload_path\x18\x01 \x01(\t\x12\x16\n\x0eload_func_name\x18\x02 \x01(\t\x12\x1a\n\x12loader_kwargs_json\x18\x03 \x01(\tB\x1cZ\x1ari/_gen/protos/rimeconfigsb\x06proto3')



_PATHTABULARINCREMENTALCONFIG = DESCRIPTOR.message_types_by_name['PathTabularIncrementalConfig']
_PATHNLPINCREMENTALCONFIG = DESCRIPTOR.message_types_by_name['PathNLPIncrementalConfig']
_PATHIMAGESINCREMENTALCONFIG = DESCRIPTOR.message_types_by_name['PathImagesIncrementalConfig']
_DATACOLLECTORINCREMENTALCONFIG = DESCRIPTOR.message_types_by_name['DataCollectorIncrementalConfig']
_DATACOLLECTORINCREMENTALCONFIG_DATACOLLECTOREVALDATAINFO = _DATACOLLECTORINCREMENTALCONFIG.nested_types_by_name['DataCollectorEvalDataInfo']
_DELTALAKEINCREMENTALCONFIG = DESCRIPTOR.message_types_by_name['DeltaLakeIncrementalConfig']
_DELTALAKEINCREMENTALCONFIG_EVALDATAINFO = _DELTALAKEINCREMENTALCONFIG.nested_types_by_name['EvalDataInfo']
_CUSTOMLOADERINCREMENTALCONFIG = DESCRIPTOR.message_types_by_name['CustomLoaderIncrementalConfig']
_CUSTOMLOADERINCREMENTALCONFIG_EVALDATAINFO = _CUSTOMLOADERINCREMENTALCONFIG.nested_types_by_name['EvalDataInfo']
PathTabularIncrementalConfig = _reflection.GeneratedProtocolMessageType('PathTabularIncrementalConfig', (_message.Message,), {
  'DESCRIPTOR' : _PATHTABULARINCREMENTALCONFIG,
  '__module__' : 'protos.rime_configs.rime_configs_pb2'
  # @@protoc_insertion_point(class_scope:rime.PathTabularIncrementalConfig)
  })
_sym_db.RegisterMessage(PathTabularIncrementalConfig)

PathNLPIncrementalConfig = _reflection.GeneratedProtocolMessageType('PathNLPIncrementalConfig', (_message.Message,), {
  'DESCRIPTOR' : _PATHNLPINCREMENTALCONFIG,
  '__module__' : 'protos.rime_configs.rime_configs_pb2'
  # @@protoc_insertion_point(class_scope:rime.PathNLPIncrementalConfig)
  })
_sym_db.RegisterMessage(PathNLPIncrementalConfig)

PathImagesIncrementalConfig = _reflection.GeneratedProtocolMessageType('PathImagesIncrementalConfig', (_message.Message,), {
  'DESCRIPTOR' : _PATHIMAGESINCREMENTALCONFIG,
  '__module__' : 'protos.rime_configs.rime_configs_pb2'
  # @@protoc_insertion_point(class_scope:rime.PathImagesIncrementalConfig)
  })
_sym_db.RegisterMessage(PathImagesIncrementalConfig)

DataCollectorIncrementalConfig = _reflection.GeneratedProtocolMessageType('DataCollectorIncrementalConfig', (_message.Message,), {

  'DataCollectorEvalDataInfo' : _reflection.GeneratedProtocolMessageType('DataCollectorEvalDataInfo', (_message.Message,), {
    'DESCRIPTOR' : _DATACOLLECTORINCREMENTALCONFIG_DATACOLLECTOREVALDATAINFO,
    '__module__' : 'protos.rime_configs.rime_configs_pb2'
    # @@protoc_insertion_point(class_scope:rime.DataCollectorIncrementalConfig.DataCollectorEvalDataInfo)
    })
  ,
  'DESCRIPTOR' : _DATACOLLECTORINCREMENTALCONFIG,
  '__module__' : 'protos.rime_configs.rime_configs_pb2'
  # @@protoc_insertion_point(class_scope:rime.DataCollectorIncrementalConfig)
  })
_sym_db.RegisterMessage(DataCollectorIncrementalConfig)
_sym_db.RegisterMessage(DataCollectorIncrementalConfig.DataCollectorEvalDataInfo)

DeltaLakeIncrementalConfig = _reflection.GeneratedProtocolMessageType('DeltaLakeIncrementalConfig', (_message.Message,), {

  'EvalDataInfo' : _reflection.GeneratedProtocolMessageType('EvalDataInfo', (_message.Message,), {
    'DESCRIPTOR' : _DELTALAKEINCREMENTALCONFIG_EVALDATAINFO,
    '__module__' : 'protos.rime_configs.rime_configs_pb2'
    # @@protoc_insertion_point(class_scope:rime.DeltaLakeIncrementalConfig.EvalDataInfo)
    })
  ,
  'DESCRIPTOR' : _DELTALAKEINCREMENTALCONFIG,
  '__module__' : 'protos.rime_configs.rime_configs_pb2'
  # @@protoc_insertion_point(class_scope:rime.DeltaLakeIncrementalConfig)
  })
_sym_db.RegisterMessage(DeltaLakeIncrementalConfig)
_sym_db.RegisterMessage(DeltaLakeIncrementalConfig.EvalDataInfo)

CustomLoaderIncrementalConfig = _reflection.GeneratedProtocolMessageType('CustomLoaderIncrementalConfig', (_message.Message,), {

  'EvalDataInfo' : _reflection.GeneratedProtocolMessageType('EvalDataInfo', (_message.Message,), {
    'DESCRIPTOR' : _CUSTOMLOADERINCREMENTALCONFIG_EVALDATAINFO,
    '__module__' : 'protos.rime_configs.rime_configs_pb2'
    # @@protoc_insertion_point(class_scope:rime.CustomLoaderIncrementalConfig.EvalDataInfo)
    })
  ,
  'DESCRIPTOR' : _CUSTOMLOADERINCREMENTALCONFIG,
  '__module__' : 'protos.rime_configs.rime_configs_pb2'
  # @@protoc_insertion_point(class_scope:rime.CustomLoaderIncrementalConfig)
  })
_sym_db.RegisterMessage(CustomLoaderIncrementalConfig)
_sym_db.RegisterMessage(CustomLoaderIncrementalConfig.EvalDataInfo)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'Z\032ri/_gen/protos/rimeconfigs'
  _DATACOLLECTORINCREMENTALCONFIG._options = None
  _DATACOLLECTORINCREMENTALCONFIG._serialized_options = b'\030\001'
  _PATHTABULARINCREMENTALCONFIG._serialized_start=49
  _PATHTABULARINCREMENTALCONFIG._serialized_end=192
  _PATHNLPINCREMENTALCONFIG._serialized_start=194
  _PATHNLPINCREMENTALCONFIG._serialized_end=310
  _PATHIMAGESINCREMENTALCONFIG._serialized_start=312
  _PATHIMAGESINCREMENTALCONFIG._serialized_end=431
  _DATACOLLECTORINCREMENTALCONFIG._serialized_start=434
  _DATACOLLECTORINCREMENTALCONFIG._serialized_end=648
  _DATACOLLECTORINCREMENTALCONFIG_DATACOLLECTOREVALDATAINFO._serialized_start=579
  _DATACOLLECTORINCREMENTALCONFIG_DATACOLLECTOREVALDATAINFO._serialized_end=644
  _DELTALAKEINCREMENTALCONFIG._serialized_start=651
  _DELTALAKEINCREMENTALCONFIG._serialized_end=910
  _DELTALAKEINCREMENTALCONFIG_EVALDATAINFO._serialized_start=776
  _DELTALAKEINCREMENTALCONFIG_EVALDATAINFO._serialized_end=910
  _CUSTOMLOADERINCREMENTALCONFIG._serialized_start=913
  _CUSTOMLOADERINCREMENTALCONFIG._serialized_end=1128
  _CUSTOMLOADERINCREMENTALCONFIG_EVALDATAINFO._serialized_start=1043
  _CUSTOMLOADERINCREMENTALCONFIG_EVALDATAINFO._serialized_end=1128
# @@protoc_insertion_point(module_scope)
