# Generated by the Protocol Buffers compiler. DO NOT EDIT!
# source: ai/lzy/v1/fs.proto
# plugin: grpclib.plugin.main
import abc
import typing

import grpclib.const
import grpclib.client
if typing.TYPE_CHECKING:
    import grpclib.server

import ai.lzy.v1.zygote_pb2
import ai.lzy.v1.fs_pb2


class LzyFsBase(abc.ABC):

    @abc.abstractmethod
    async def CreateSlot(self, stream: 'grpclib.server.Stream[ai.lzy.v1.fs_pb2.CreateSlotRequest, ai.lzy.v1.fs_pb2.SlotCommandStatus]') -> None:
        pass

    @abc.abstractmethod
    async def ConnectSlot(self, stream: 'grpclib.server.Stream[ai.lzy.v1.fs_pb2.ConnectSlotRequest, ai.lzy.v1.fs_pb2.SlotCommandStatus]') -> None:
        pass

    @abc.abstractmethod
    async def DisconnectSlot(self, stream: 'grpclib.server.Stream[ai.lzy.v1.fs_pb2.DisconnectSlotRequest, ai.lzy.v1.fs_pb2.SlotCommandStatus]') -> None:
        pass

    @abc.abstractmethod
    async def StatusSlot(self, stream: 'grpclib.server.Stream[ai.lzy.v1.fs_pb2.StatusSlotRequest, ai.lzy.v1.fs_pb2.SlotCommandStatus]') -> None:
        pass

    @abc.abstractmethod
    async def DestroySlot(self, stream: 'grpclib.server.Stream[ai.lzy.v1.fs_pb2.DestroySlotRequest, ai.lzy.v1.fs_pb2.SlotCommandStatus]') -> None:
        pass

    @abc.abstractmethod
    async def OpenOutputSlot(self, stream: 'grpclib.server.Stream[ai.lzy.v1.fs_pb2.SlotRequest, ai.lzy.v1.fs_pb2.Message]') -> None:
        pass

    def __mapping__(self) -> typing.Dict[str, grpclib.const.Handler]:
        return {
            '/ai.lzy.v1.LzyFs/CreateSlot': grpclib.const.Handler(
                self.CreateSlot,
                grpclib.const.Cardinality.UNARY_UNARY,
                ai.lzy.v1.fs_pb2.CreateSlotRequest,
                ai.lzy.v1.fs_pb2.SlotCommandStatus,
            ),
            '/ai.lzy.v1.LzyFs/ConnectSlot': grpclib.const.Handler(
                self.ConnectSlot,
                grpclib.const.Cardinality.UNARY_UNARY,
                ai.lzy.v1.fs_pb2.ConnectSlotRequest,
                ai.lzy.v1.fs_pb2.SlotCommandStatus,
            ),
            '/ai.lzy.v1.LzyFs/DisconnectSlot': grpclib.const.Handler(
                self.DisconnectSlot,
                grpclib.const.Cardinality.UNARY_UNARY,
                ai.lzy.v1.fs_pb2.DisconnectSlotRequest,
                ai.lzy.v1.fs_pb2.SlotCommandStatus,
            ),
            '/ai.lzy.v1.LzyFs/StatusSlot': grpclib.const.Handler(
                self.StatusSlot,
                grpclib.const.Cardinality.UNARY_UNARY,
                ai.lzy.v1.fs_pb2.StatusSlotRequest,
                ai.lzy.v1.fs_pb2.SlotCommandStatus,
            ),
            '/ai.lzy.v1.LzyFs/DestroySlot': grpclib.const.Handler(
                self.DestroySlot,
                grpclib.const.Cardinality.UNARY_UNARY,
                ai.lzy.v1.fs_pb2.DestroySlotRequest,
                ai.lzy.v1.fs_pb2.SlotCommandStatus,
            ),
            '/ai.lzy.v1.LzyFs/OpenOutputSlot': grpclib.const.Handler(
                self.OpenOutputSlot,
                grpclib.const.Cardinality.UNARY_STREAM,
                ai.lzy.v1.fs_pb2.SlotRequest,
                ai.lzy.v1.fs_pb2.Message,
            ),
        }


class LzyFsStub:

    def __init__(self, channel: grpclib.client.Channel) -> None:
        self.CreateSlot = grpclib.client.UnaryUnaryMethod(
            channel,
            '/ai.lzy.v1.LzyFs/CreateSlot',
            ai.lzy.v1.fs_pb2.CreateSlotRequest,
            ai.lzy.v1.fs_pb2.SlotCommandStatus,
        )
        self.ConnectSlot = grpclib.client.UnaryUnaryMethod(
            channel,
            '/ai.lzy.v1.LzyFs/ConnectSlot',
            ai.lzy.v1.fs_pb2.ConnectSlotRequest,
            ai.lzy.v1.fs_pb2.SlotCommandStatus,
        )
        self.DisconnectSlot = grpclib.client.UnaryUnaryMethod(
            channel,
            '/ai.lzy.v1.LzyFs/DisconnectSlot',
            ai.lzy.v1.fs_pb2.DisconnectSlotRequest,
            ai.lzy.v1.fs_pb2.SlotCommandStatus,
        )
        self.StatusSlot = grpclib.client.UnaryUnaryMethod(
            channel,
            '/ai.lzy.v1.LzyFs/StatusSlot',
            ai.lzy.v1.fs_pb2.StatusSlotRequest,
            ai.lzy.v1.fs_pb2.SlotCommandStatus,
        )
        self.DestroySlot = grpclib.client.UnaryUnaryMethod(
            channel,
            '/ai.lzy.v1.LzyFs/DestroySlot',
            ai.lzy.v1.fs_pb2.DestroySlotRequest,
            ai.lzy.v1.fs_pb2.SlotCommandStatus,
        )
        self.OpenOutputSlot = grpclib.client.UnaryStreamMethod(
            channel,
            '/ai.lzy.v1.LzyFs/OpenOutputSlot',
            ai.lzy.v1.fs_pb2.SlotRequest,
            ai.lzy.v1.fs_pb2.Message,
        )
