
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-08-25T17:42:44+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "1c1fe78181fcb08629b7e1d1e67d519f816e889f",
 "version": "v22.10.00a220828"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
