# coding: utf-8

"""
    ZIOS api

    ZIOS operations  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six

from zios.configuration import Configuration


class Body4(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'request_action': 'str',
        'arguments': 'object'
    }

    attribute_map = {
        'request_action': 'request_action',
        'arguments': 'arguments'
    }

    def __init__(self, request_action=None, arguments=None, _configuration=None):  # noqa: E501
        """Body4 - a model defined in Swagger"""  # noqa: E501
        if _configuration is None:
            _configuration = Configuration()
        self._configuration = _configuration

        self._request_action = None
        self._arguments = None
        self.discriminator = None

        self.request_action = request_action
        self.arguments = arguments

    @property
    def request_action(self):
        """Gets the request_action of this Body4.  # noqa: E501


        :return: The request_action of this Body4.  # noqa: E501
        :rtype: str
        """
        return self._request_action

    @request_action.setter
    def request_action(self, request_action):
        """Sets the request_action of this Body4.


        :param request_action: The request_action of this Body4.  # noqa: E501
        :type: str
        """
        if self._configuration.client_side_validation and request_action is None:
            raise ValueError("Invalid value for `request_action`, must not be `None`")  # noqa: E501

        self._request_action = request_action

    @property
    def arguments(self):
        """Gets the arguments of this Body4.  # noqa: E501


        :return: The arguments of this Body4.  # noqa: E501
        :rtype: object
        """
        return self._arguments

    @arguments.setter
    def arguments(self, arguments):
        """Sets the arguments of this Body4.


        :param arguments: The arguments of this Body4.  # noqa: E501
        :type: object
        """
        if self._configuration.client_side_validation and arguments is None:
            raise ValueError("Invalid value for `arguments`, must not be `None`")  # noqa: E501

        self._arguments = arguments

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(Body4, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, Body4):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, Body4):
            return True

        return self.to_dict() != other.to_dict()
