# coding: utf-8

"""
    ZIOS api

    ZIOS operations  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six

from zios.configuration import Configuration


class InlineResponse2006Response(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'message': 'str',
        'count': 'int',
        'requests': 'list[InlineResponse2006ResponseRequests]'
    }

    attribute_map = {
        'message': 'message',
        'count': 'count',
        'requests': 'requests'
    }

    def __init__(self, message=None, count=None, requests=None, _configuration=None):  # noqa: E501
        """InlineResponse2006Response - a model defined in Swagger"""  # noqa: E501
        if _configuration is None:
            _configuration = Configuration()
        self._configuration = _configuration

        self._message = None
        self._count = None
        self._requests = None
        self.discriminator = None

        if message is not None:
            self.message = message
        if count is not None:
            self.count = count
        if requests is not None:
            self.requests = requests

    @property
    def message(self):
        """Gets the message of this InlineResponse2006Response.  # noqa: E501


        :return: The message of this InlineResponse2006Response.  # noqa: E501
        :rtype: str
        """
        return self._message

    @message.setter
    def message(self, message):
        """Sets the message of this InlineResponse2006Response.


        :param message: The message of this InlineResponse2006Response.  # noqa: E501
        :type: str
        """

        self._message = message

    @property
    def count(self):
        """Gets the count of this InlineResponse2006Response.  # noqa: E501


        :return: The count of this InlineResponse2006Response.  # noqa: E501
        :rtype: int
        """
        return self._count

    @count.setter
    def count(self, count):
        """Sets the count of this InlineResponse2006Response.


        :param count: The count of this InlineResponse2006Response.  # noqa: E501
        :type: int
        """

        self._count = count

    @property
    def requests(self):
        """Gets the requests of this InlineResponse2006Response.  # noqa: E501


        :return: The requests of this InlineResponse2006Response.  # noqa: E501
        :rtype: list[InlineResponse2006ResponseRequests]
        """
        return self._requests

    @requests.setter
    def requests(self, requests):
        """Sets the requests of this InlineResponse2006Response.


        :param requests: The requests of this InlineResponse2006Response.  # noqa: E501
        :type: list[InlineResponse2006ResponseRequests]
        """

        self._requests = requests

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(InlineResponse2006Response, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, InlineResponse2006Response):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, InlineResponse2006Response):
            return True

        return self.to_dict() != other.to_dict()
