# coding: utf-8

"""
    ZIOS api

    ZIOS operations  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six

from zios.configuration import Configuration


class InlineResponse20034ResponseZiosData(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'zios_user': 'InlineResponse20034ResponseZiosDataZiosUser'
    }

    attribute_map = {
        'zios_user': 'zios_user'
    }

    def __init__(self, zios_user=None, _configuration=None):  # noqa: E501
        """InlineResponse20034ResponseZiosData - a model defined in Swagger"""  # noqa: E501
        if _configuration is None:
            _configuration = Configuration()
        self._configuration = _configuration

        self._zios_user = None
        self.discriminator = None

        if zios_user is not None:
            self.zios_user = zios_user

    @property
    def zios_user(self):
        """Gets the zios_user of this InlineResponse20034ResponseZiosData.  # noqa: E501


        :return: The zios_user of this InlineResponse20034ResponseZiosData.  # noqa: E501
        :rtype: InlineResponse20034ResponseZiosDataZiosUser
        """
        return self._zios_user

    @zios_user.setter
    def zios_user(self, zios_user):
        """Sets the zios_user of this InlineResponse20034ResponseZiosData.


        :param zios_user: The zios_user of this InlineResponse20034ResponseZiosData.  # noqa: E501
        :type: InlineResponse20034ResponseZiosDataZiosUser
        """

        self._zios_user = zios_user

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(InlineResponse20034ResponseZiosData, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, InlineResponse20034ResponseZiosData):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, InlineResponse20034ResponseZiosData):
            return True

        return self.to_dict() != other.to_dict()
