# coding: utf-8

"""
    ZIOS api

    ZIOS operations  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import zios
from zios.api.container_replication_api import ContainerReplicationApi  # noqa: E501
from zios.rest import ApiException


class TestContainerReplicationApi(unittest.TestCase):
    """ContainerReplicationApi unit test stubs"""

    def setUp(self):
        self.api = zios.api.container_replication_api.ContainerReplicationApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_create_container_replication_job(self):
        """Test case for create_container_replication_job

        """
        pass

    def test_delete_container_replication_job(self):
        """Test case for delete_container_replication_job

        """
        pass

    def test_get_container_replication_job(self):
        """Test case for get_container_replication_job

        """
        pass

    def test_get_stats_of_container_replication_job(self):
        """Test case for get_stats_of_container_replication_job

        """
        pass

    def test_get_stats_of_replication_job(self):
        """Test case for get_stats_of_replication_job

        """
        pass

    def test_pause_container_replication_job(self):
        """Test case for pause_container_replication_job

        """
        pass

    def test_reaume_container_replication_job(self):
        """Test case for reaume_container_replication_job

        """
        pass


if __name__ == '__main__':
    unittest.main()
