
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-09-02T15:21:20+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "fe8d8da0e176317c21cec52024024b8019ec2498",
 "version": "2746"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
