from django.conf import settings

CLICKHOUSE_LOGGER_HOST = getattr(settings, 'CLICKHOUSE_LOGGER_HOST', None)
CLICKHOUSE_LOGGER_PORT = getattr(settings, 'CLICKHOUSE_LOGGER_PORT', 9000)
CLICKHOUSE_LOGGER_USER = getattr(settings, 'CLICKHOUSE_LOGGER_USER', 'default')
CLICKHOUSE_LOGGER_PASSWORD = getattr(settings, 'CLICKHOUSE_LOGGER_PASSWORD', '')
CLICKHOUSE_LOGGER_TTL_DAY = getattr(settings, 'CLICKHOUSE_LOGGER_TTL_DAY', 1)
CLICKHOUSE_LOGGER_REQUEST_EXTRA = getattr(settings, 'CLICKHOUSE_LOGGER_REQUEST_EXTRA', 'session')
