# coding: utf-8

"""
    CC api

    Command Center operations  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import cc
from cc.models.inline_response200101_master_vc import InlineResponse200101MasterVc  # noqa: E501
from cc.rest import ApiException


class TestInlineResponse200101MasterVc(unittest.TestCase):
    """InlineResponse200101MasterVc unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testInlineResponse200101MasterVc(self):
        """Test InlineResponse200101MasterVc"""
        # FIXME: construct object with mandatory attributes with example values
        # model = cc.models.inline_response200101_master_vc.InlineResponse200101MasterVc()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
