# coding: utf-8

"""
    CC api

    Command Center operations  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import cc
from cc.models.inline_response20066 import InlineResponse20066  # noqa: E501
from cc.rest import ApiException


class TestInlineResponse20066(unittest.TestCase):
    """InlineResponse20066 unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testInlineResponse20066(self):
        """Test InlineResponse20066"""
        # FIXME: construct object with mandatory attributes with example values
        # model = cc.models.inline_response20066.InlineResponse20066()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
