# coding: utf-8

"""
    CC api

    Command Center operations  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import cc
from cc.models.inline_response20061 import InlineResponse20061  # noqa: E501
from cc.rest import ApiException


class TestInlineResponse20061(unittest.TestCase):
    """InlineResponse20061 unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testInlineResponse20061(self):
        """Test InlineResponse20061"""
        # FIXME: construct object with mandatory attributes with example values
        # model = cc.models.inline_response20061.InlineResponse20061()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
