# coding: utf-8

"""
    CC api

    Command Center operations  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import cc
from cc.models.inline_response20014_custom_network import InlineResponse20014CustomNetwork  # noqa: E501
from cc.rest import ApiException


class TestInlineResponse20014CustomNetwork(unittest.TestCase):
    """InlineResponse20014CustomNetwork unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testInlineResponse20014CustomNetwork(self):
        """Test InlineResponse20014CustomNetwork"""
        # FIXME: construct object with mandatory attributes with example values
        # model = cc.models.inline_response20014_custom_network.InlineResponse20014CustomNetwork()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
