# coding: utf-8

"""
    CC api

    Command Center operations  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import cc
from cc.models.inline_response200107 import InlineResponse200107  # noqa: E501
from cc.rest import ApiException


class TestInlineResponse200107(unittest.TestCase):
    """InlineResponse200107 unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testInlineResponse200107(self):
        """Test InlineResponse200107"""
        # FIXME: construct object with mandatory attributes with example values
        # model = cc.models.inline_response200107.InlineResponse200107()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
