# coding: utf-8

"""
    CC api

    Command Center operations  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import cc
from cc.models.inline_response20053_user_roles import InlineResponse20053UserRoles  # noqa: E501
from cc.rest import ApiException


class TestInlineResponse20053UserRoles(unittest.TestCase):
    """InlineResponse20053UserRoles unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testInlineResponse20053UserRoles(self):
        """Test InlineResponse20053UserRoles"""
        # FIXME: construct object with mandatory attributes with example values
        # model = cc.models.inline_response20053_user_roles.InlineResponse20053UserRoles()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
