# coding: utf-8

"""
    CC api

    Command Center operations  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import cc
from cc.models.inline_response20064 import InlineResponse20064  # noqa: E501
from cc.rest import ApiException


class TestInlineResponse20064(unittest.TestCase):
    """InlineResponse20064 unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testInlineResponse20064(self):
        """Test InlineResponse20064"""
        # FIXME: construct object with mandatory attributes with example values
        # model = cc.models.inline_response20064.InlineResponse20064()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
