
# This file was generated by 'versioneer.py' (0.21) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-09-01T21:45:31-0400",
 "dirty": false,
 "error": null,
 "full-revisionid": "5be0af288c796c1eb5ecf996ff7d462a5971ca24",
 "version": "0.1.0a72"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
