# coding: utf-8

"""
    vsc

    Provides VSC APIs  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import vsc
from vsc.api.storageclass_api import StorageclassApi  # noqa: E501
from vsc.rest import ApiException


class TestStorageclassApi(unittest.TestCase):
    """StorageclassApi unit test stubs"""

    def setUp(self):
        self.api = vsc.api.storageclass_api.StorageclassApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_add_storage_class_member(self):
        """Test case for add_storage_class_member

        Add VPSA as a member of Storage Class  # noqa: E501
        """
        pass

    def test_create_storage_class(self):
        """Test case for create_storage_class

        Create a new VSC StorageClass  # noqa: E501
        """
        pass

    def test_delete_storage_class(self):
        """Test case for delete_storage_class

        Delete Storage Class  # noqa: E501
        """
        pass

    def test_get_one_storage_class(self):
        """Test case for get_one_storage_class

        Get a specific Storage Class  # noqa: E501
        """
        pass

    def test_get_one_storage_class_member(self):
        """Test case for get_one_storage_class_member

        Get a Storage Class member details  # noqa: E501
        """
        pass

    def test_get_storage_class_members(self):
        """Test case for get_storage_class_members

        Get Storage Class members  # noqa: E501
        """
        pass

    def test_get_storage_classes(self):
        """Test case for get_storage_classes

        Get VSC Storage Classes  # noqa: E501
        """
        pass

    def test_remove_storage_class_member(self):
        """Test case for remove_storage_class_member

        Remove a Storage Class Member  # noqa: E501
        """
        pass

    def test_update_storage_class(self):
        """Test case for update_storage_class

        Update properties of a Storage Class  # noqa: E501
        """
        pass

    def test_update_storage_class_member(self):
        """Test case for update_storage_class_member

        Update Storage Class member properties  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
