# -*- coding: utf-8 -*-
from setuptools import setup

packages = \
['dbpedia_ent',
 'dbpedia_ent.bp',
 'dbpedia_ent.dmo',
 'dbpedia_ent.dto',
 'dbpedia_ent.dto.n1',
 'dbpedia_ent.dto.n1.a',
 'dbpedia_ent.dto.n1.b',
 'dbpedia_ent.dto.n1.c',
 'dbpedia_ent.dto.n1.d',
 'dbpedia_ent.dto.n1.e',
 'dbpedia_ent.dto.n1.f',
 'dbpedia_ent.dto.n1.g',
 'dbpedia_ent.dto.n1.h',
 'dbpedia_ent.dto.n1.i',
 'dbpedia_ent.dto.n1.j',
 'dbpedia_ent.dto.n1.k',
 'dbpedia_ent.dto.n1.l',
 'dbpedia_ent.dto.n1.m',
 'dbpedia_ent.dto.n1.n',
 'dbpedia_ent.dto.n1.o',
 'dbpedia_ent.dto.n1.p',
 'dbpedia_ent.dto.n1.q',
 'dbpedia_ent.dto.n1.r',
 'dbpedia_ent.dto.n1.s',
 'dbpedia_ent.dto.n1.t',
 'dbpedia_ent.dto.n1.u',
 'dbpedia_ent.dto.n1.v',
 'dbpedia_ent.dto.n1.w',
 'dbpedia_ent.dto.n1.x',
 'dbpedia_ent.dto.n1.y',
 'dbpedia_ent.dto.n1.z',
 'dbpedia_ent.dto.n2.a',
 'dbpedia_ent.dto.n2.b',
 'dbpedia_ent.dto.n2.c',
 'dbpedia_ent.dto.n2.d',
 'dbpedia_ent.dto.n2.e',
 'dbpedia_ent.dto.n2.f',
 'dbpedia_ent.dto.n2.g',
 'dbpedia_ent.dto.n2.h',
 'dbpedia_ent.dto.n2.i',
 'dbpedia_ent.dto.n2.j',
 'dbpedia_ent.dto.n2.k',
 'dbpedia_ent.dto.n2.l',
 'dbpedia_ent.dto.n2.m',
 'dbpedia_ent.dto.n2.n',
 'dbpedia_ent.dto.n2.o',
 'dbpedia_ent.dto.n2.p',
 'dbpedia_ent.dto.n2.q',
 'dbpedia_ent.dto.n2.r',
 'dbpedia_ent.dto.n2.s',
 'dbpedia_ent.dto.n2.t',
 'dbpedia_ent.dto.n2.u',
 'dbpedia_ent.dto.n2.v',
 'dbpedia_ent.dto.n2.w',
 'dbpedia_ent.dto.n2.x',
 'dbpedia_ent.dto.n2.y',
 'dbpedia_ent.dto.n2.z',
 'dbpedia_ent.dto.n3.a',
 'dbpedia_ent.dto.n3.b',
 'dbpedia_ent.dto.n3.c',
 'dbpedia_ent.dto.n3.d',
 'dbpedia_ent.dto.n3.e',
 'dbpedia_ent.dto.n3.f',
 'dbpedia_ent.dto.n3.g',
 'dbpedia_ent.dto.n3.h',
 'dbpedia_ent.dto.n3.i',
 'dbpedia_ent.dto.n3.j',
 'dbpedia_ent.dto.n3.k',
 'dbpedia_ent.dto.n3.l',
 'dbpedia_ent.dto.n3.m',
 'dbpedia_ent.dto.n3.n',
 'dbpedia_ent.dto.n3.o',
 'dbpedia_ent.dto.n3.p',
 'dbpedia_ent.dto.n3.q',
 'dbpedia_ent.dto.n3.r',
 'dbpedia_ent.dto.n3.s',
 'dbpedia_ent.dto.n3.t',
 'dbpedia_ent.dto.n3.u',
 'dbpedia_ent.dto.n3.v',
 'dbpedia_ent.dto.n3.w',
 'dbpedia_ent.dto.n3.x',
 'dbpedia_ent.dto.n3.y',
 'dbpedia_ent.dto.n3.z',
 'dbpedia_ent.svc']

package_data = \
{'': ['*']}

install_requires = \
['baseblock', 'unicodedata2']

setup_kwargs = {
    'name': 'dbpedia-ent',
    'version': '0.1.4',
    'description': 'Static dbPedia Entities for Fast Lookups',
    'long_description': None,
    'author': 'Craig Trim',
    'author_email': 'craig.trim@causalitylink.com',
    'maintainer': None,
    'maintainer_email': None,
    'url': None,
    'packages': packages,
    'package_data': package_data,
    'install_requires': install_requires,
    'python_requires': '==3.8.5',
}


setup(**setup_kwargs)
