VERSION_YEAR = 2022
VERSION_MONTH = int('08')
VERSION_DAY = int('30')
VERSION_HOUR = int('14')
VERSION_MINUTE = int('33')
MAJOR_VERSION = 1
MINOR_VERSION = 10
PATCH_VERSION = 202208301433
version_date = '2022/08/30 14:33'
version = '{}.{}.{}'.format(MAJOR_VERSION, MINOR_VERSION, PATCH_VERSION)
__all__  = ['MAJOR_VERSION', 'MINOR_VERSION', 'PATCH_VERSION', 'version_date', 'version']
