
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-08-31T10:52:52-0400",
 "dirty": false,
 "error": null,
 "full-revisionid": "7e8058f4c821519da7ae26a890f92c253ed6a0bf",
 "version": "2022.8.1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
