
# This file was generated by 'versioneer.py' (0.23) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-08-31T09:10:57+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "1e20eae61128e76cb5ed360ad28b2ae4ff6a4c9b",
 "version": "1.17.0.post0.dev208"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
