# coding: utf-8

"""
    vsc

    Provides VSC APIs  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six

from vsc.configuration import Configuration


class StorageClassCreateRequest(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'client_token': 'str',
        'description': 'str',
        'is_default': 'bool',
        'name': 'str',
        'volume_creation_flags': 'VolumeFlags'
    }

    attribute_map = {
        'client_token': 'client_token',
        'description': 'description',
        'is_default': 'is_default',
        'name': 'name',
        'volume_creation_flags': 'volume_creation_flags'
    }

    def __init__(self, client_token=None, description=None, is_default=None, name=None, volume_creation_flags=None, _configuration=None):  # noqa: E501
        """StorageClassCreateRequest - a model defined in Swagger"""  # noqa: E501
        if _configuration is None:
            _configuration = Configuration()
        self._configuration = _configuration

        self._client_token = None
        self._description = None
        self._is_default = None
        self._name = None
        self._volume_creation_flags = None
        self.discriminator = None

        if client_token is not None:
            self.client_token = client_token
        if description is not None:
            self.description = description
        if is_default is not None:
            self.is_default = is_default
        self.name = name
        if volume_creation_flags is not None:
            self.volume_creation_flags = volume_creation_flags

    @property
    def client_token(self):
        """Gets the client_token of this StorageClassCreateRequest.  # noqa: E501

        request token to ensure the idempotency of the request  # noqa: E501

        :return: The client_token of this StorageClassCreateRequest.  # noqa: E501
        :rtype: str
        """
        return self._client_token

    @client_token.setter
    def client_token(self, client_token):
        """Sets the client_token of this StorageClassCreateRequest.

        request token to ensure the idempotency of the request  # noqa: E501

        :param client_token: The client_token of this StorageClassCreateRequest.  # noqa: E501
        :type: str
        """

        self._client_token = client_token

    @property
    def description(self):
        """Gets the description of this StorageClassCreateRequest.  # noqa: E501

        Description of Storage Class  # noqa: E501

        :return: The description of this StorageClassCreateRequest.  # noqa: E501
        :rtype: str
        """
        return self._description

    @description.setter
    def description(self, description):
        """Sets the description of this StorageClassCreateRequest.

        Description of Storage Class  # noqa: E501

        :param description: The description of this StorageClassCreateRequest.  # noqa: E501
        :type: str
        """

        self._description = description

    @property
    def is_default(self):
        """Gets the is_default of this StorageClassCreateRequest.  # noqa: E501

        Set Storage class as default  # noqa: E501

        :return: The is_default of this StorageClassCreateRequest.  # noqa: E501
        :rtype: bool
        """
        return self._is_default

    @is_default.setter
    def is_default(self, is_default):
        """Sets the is_default of this StorageClassCreateRequest.

        Set Storage class as default  # noqa: E501

        :param is_default: The is_default of this StorageClassCreateRequest.  # noqa: E501
        :type: bool
        """

        self._is_default = is_default

    @property
    def name(self):
        """Gets the name of this StorageClassCreateRequest.  # noqa: E501

        Name of Storage Class  # noqa: E501

        :return: The name of this StorageClassCreateRequest.  # noqa: E501
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this StorageClassCreateRequest.

        Name of Storage Class  # noqa: E501

        :param name: The name of this StorageClassCreateRequest.  # noqa: E501
        :type: str
        """
        if self._configuration.client_side_validation and name is None:
            raise ValueError("Invalid value for `name`, must not be `None`")  # noqa: E501

        self._name = name

    @property
    def volume_creation_flags(self):
        """Gets the volume_creation_flags of this StorageClassCreateRequest.  # noqa: E501

        Volume Creation Flags  # noqa: E501

        :return: The volume_creation_flags of this StorageClassCreateRequest.  # noqa: E501
        :rtype: VolumeFlags
        """
        return self._volume_creation_flags

    @volume_creation_flags.setter
    def volume_creation_flags(self, volume_creation_flags):
        """Sets the volume_creation_flags of this StorageClassCreateRequest.

        Volume Creation Flags  # noqa: E501

        :param volume_creation_flags: The volume_creation_flags of this StorageClassCreateRequest.  # noqa: E501
        :type: VolumeFlags
        """

        self._volume_creation_flags = volume_creation_flags

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(StorageClassCreateRequest, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, StorageClassCreateRequest):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, StorageClassCreateRequest):
            return True

        return self.to_dict() != other.to_dict()
