
# This file was generated by 'versioneer.py' (0.23) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-08-31T14:20:18-0400",
 "dirty": false,
 "error": null,
 "full-revisionid": "dfec98a53ad2e2f80810b062c3b8a143291cea41",
 "version": "1.2.3"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
