
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-09-01T10:50:48+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "650abf09cadc8f374a06d41a4f32502cb0ee383a",
 "version": "2742"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
