# coding: utf-8

"""
    VPSA api

    VPSA operations  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import vpsa
from vpsa.models.inline_response200167_response import InlineResponse200167Response  # noqa: E501
from vpsa.rest import ApiException


class TestInlineResponse200167Response(unittest.TestCase):
    """InlineResponse200167Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testInlineResponse200167Response(self):
        """Test InlineResponse200167Response"""
        # FIXME: construct object with mandatory attributes with example values
        # model = vpsa.models.inline_response200167_response.InlineResponse200167Response()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
