# coding: utf-8

"""
    VPSA api

    VPSA operations  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import vpsa
from vpsa.models.inline_response20085_response_obs_destination import InlineResponse20085ResponseObsDestination  # noqa: E501
from vpsa.rest import ApiException


class TestInlineResponse20085ResponseObsDestination(unittest.TestCase):
    """InlineResponse20085ResponseObsDestination unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testInlineResponse20085ResponseObsDestination(self):
        """Test InlineResponse20085ResponseObsDestination"""
        # FIXME: construct object with mandatory attributes with example values
        # model = vpsa.models.inline_response20085_response_obs_destination.InlineResponse20085ResponseObsDestination()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
