# coding: utf-8

"""
    VPSA api

    VPSA operations  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import vpsa
from vpsa.models.inline_response200169 import InlineResponse200169  # noqa: E501
from vpsa.rest import ApiException


class TestInlineResponse200169(unittest.TestCase):
    """InlineResponse200169 unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testInlineResponse200169(self):
        """Test InlineResponse200169"""
        # FIXME: construct object with mandatory attributes with example values
        # model = vpsa.models.inline_response200169.InlineResponse200169()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
