# coding: utf-8

"""
    VPSA api

    VPSA operations  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import vpsa
from vpsa.models.inline_response20060_response_raid_group import InlineResponse20060ResponseRaidGroup  # noqa: E501
from vpsa.rest import ApiException


class TestInlineResponse20060ResponseRaidGroup(unittest.TestCase):
    """InlineResponse20060ResponseRaidGroup unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testInlineResponse20060ResponseRaidGroup(self):
        """Test InlineResponse20060ResponseRaidGroup"""
        # FIXME: construct object with mandatory attributes with example values
        # model = vpsa.models.inline_response20060_response_raid_group.InlineResponse20060ResponseRaidGroup()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
