# coding: utf-8

"""
    VPSA api

    VPSA operations  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import vpsa
from vpsa.models.inline_response2003_response_policy_ods_exclude_file_types import InlineResponse2003ResponsePolicyOdsExcludeFileTypes  # noqa: E501
from vpsa.rest import ApiException


class TestInlineResponse2003ResponsePolicyOdsExcludeFileTypes(unittest.TestCase):
    """InlineResponse2003ResponsePolicyOdsExcludeFileTypes unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testInlineResponse2003ResponsePolicyOdsExcludeFileTypes(self):
        """Test InlineResponse2003ResponsePolicyOdsExcludeFileTypes"""
        # FIXME: construct object with mandatory attributes with example values
        # model = vpsa.models.inline_response2003_response_policy_ods_exclude_file_types.InlineResponse2003ResponsePolicyOdsExcludeFileTypes()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
