# coding: utf-8

"""
    VPSA api

    VPSA operations  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import vpsa
from vpsa.models.inline_response200131 import InlineResponse200131  # noqa: E501
from vpsa.rest import ApiException


class TestInlineResponse200131(unittest.TestCase):
    """InlineResponse200131 unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testInlineResponse200131(self):
        """Test InlineResponse200131"""
        # FIXME: construct object with mandatory attributes with example values
        # model = vpsa.models.inline_response200131.InlineResponse200131()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
