# coding: utf-8

"""
    VPSA api

    VPSA operations  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import vpsa
from vpsa.models.body77 import Body77  # noqa: E501
from vpsa.rest import ApiException


class TestBody77(unittest.TestCase):
    """Body77 unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testBody77(self):
        """Test Body77"""
        # FIXME: construct object with mandatory attributes with example values
        # model = vpsa.models.body77.Body77()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
