# coding: utf-8

"""
    VPSA api

    VPSA operations  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import vpsa
from vpsa.models.inline_response20052_response_pool_ssd import InlineResponse20052ResponsePoolSsd  # noqa: E501
from vpsa.rest import ApiException


class TestInlineResponse20052ResponsePoolSsd(unittest.TestCase):
    """InlineResponse20052ResponsePoolSsd unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testInlineResponse20052ResponsePoolSsd(self):
        """Test InlineResponse20052ResponsePoolSsd"""
        # FIXME: construct object with mandatory attributes with example values
        # model = vpsa.models.inline_response20052_response_pool_ssd.InlineResponse20052ResponsePoolSsd()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
