
# This file was generated by 'versioneer.py' (0.22) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-08-30T20:23:34+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "58ffce9e19ea856adcb97e241212f64a2c011526",
 "version": "1.43.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
