# coding: utf-8

"""
    VPSA api

    VPSA operations  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six

from vpsa.configuration import Configuration


class InlineResponse20041ResponseUsers(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'name': 'str',
        'nfs_uid': 'str',
        'password': 'str'
    }

    attribute_map = {
        'name': 'name',
        'nfs_uid': 'nfs_uid',
        'password': 'password'
    }

    def __init__(self, name=None, nfs_uid=None, password=None, _configuration=None):  # noqa: E501
        """InlineResponse20041ResponseUsers - a model defined in Swagger"""  # noqa: E501
        if _configuration is None:
            _configuration = Configuration()
        self._configuration = _configuration

        self._name = None
        self._nfs_uid = None
        self._password = None
        self.discriminator = None

        if name is not None:
            self.name = name
        if nfs_uid is not None:
            self.nfs_uid = nfs_uid
        if password is not None:
            self.password = password

    @property
    def name(self):
        """Gets the name of this InlineResponse20041ResponseUsers.  # noqa: E501


        :return: The name of this InlineResponse20041ResponseUsers.  # noqa: E501
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this InlineResponse20041ResponseUsers.


        :param name: The name of this InlineResponse20041ResponseUsers.  # noqa: E501
        :type: str
        """

        self._name = name

    @property
    def nfs_uid(self):
        """Gets the nfs_uid of this InlineResponse20041ResponseUsers.  # noqa: E501


        :return: The nfs_uid of this InlineResponse20041ResponseUsers.  # noqa: E501
        :rtype: str
        """
        return self._nfs_uid

    @nfs_uid.setter
    def nfs_uid(self, nfs_uid):
        """Sets the nfs_uid of this InlineResponse20041ResponseUsers.


        :param nfs_uid: The nfs_uid of this InlineResponse20041ResponseUsers.  # noqa: E501
        :type: str
        """

        self._nfs_uid = nfs_uid

    @property
    def password(self):
        """Gets the password of this InlineResponse20041ResponseUsers.  # noqa: E501


        :return: The password of this InlineResponse20041ResponseUsers.  # noqa: E501
        :rtype: str
        """
        return self._password

    @password.setter
    def password(self, password):
        """Sets the password of this InlineResponse20041ResponseUsers.


        :param password: The password of this InlineResponse20041ResponseUsers.  # noqa: E501
        :type: str
        """

        self._password = password

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(InlineResponse20041ResponseUsers, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, InlineResponse20041ResponseUsers):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, InlineResponse20041ResponseUsers):
            return True

        return self.to_dict() != other.to_dict()
