# coding: utf-8

"""
    VPSA api

    VPSA operations  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six

from vpsa.configuration import Configuration


class InlineResponse20045ResponseGroups(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'name': 'str',
        'nfs_gid': 'str'
    }

    attribute_map = {
        'name': 'name',
        'nfs_gid': 'nfs_gid'
    }

    def __init__(self, name=None, nfs_gid=None, _configuration=None):  # noqa: E501
        """InlineResponse20045ResponseGroups - a model defined in Swagger"""  # noqa: E501
        if _configuration is None:
            _configuration = Configuration()
        self._configuration = _configuration

        self._name = None
        self._nfs_gid = None
        self.discriminator = None

        if name is not None:
            self.name = name
        if nfs_gid is not None:
            self.nfs_gid = nfs_gid

    @property
    def name(self):
        """Gets the name of this InlineResponse20045ResponseGroups.  # noqa: E501


        :return: The name of this InlineResponse20045ResponseGroups.  # noqa: E501
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this InlineResponse20045ResponseGroups.


        :param name: The name of this InlineResponse20045ResponseGroups.  # noqa: E501
        :type: str
        """

        self._name = name

    @property
    def nfs_gid(self):
        """Gets the nfs_gid of this InlineResponse20045ResponseGroups.  # noqa: E501


        :return: The nfs_gid of this InlineResponse20045ResponseGroups.  # noqa: E501
        :rtype: str
        """
        return self._nfs_gid

    @nfs_gid.setter
    def nfs_gid(self, nfs_gid):
        """Sets the nfs_gid of this InlineResponse20045ResponseGroups.


        :param nfs_gid: The nfs_gid of this InlineResponse20045ResponseGroups.  # noqa: E501
        :type: str
        """

        self._nfs_gid = nfs_gid

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(InlineResponse20045ResponseGroups, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, InlineResponse20045ResponseGroups):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, InlineResponse20045ResponseGroups):
            return True

        return self.to_dict() != other.to_dict()
